# Generated by Django 6.1 on 2026-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('horario', models.CharField(blank=True, max_length=150, verbose_name='Horario de atención')),
                ('activa', models.BooleanField(default=True, verbose_name='Sucursal activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
    ]
